Soma
KailaneSC/AtividadeA-gqso pull request #5
Opened 2021-08-19 12:23 UTC by KailaneSC

2021-09-07 15:23 UTC, Angelina0liveira commented on calcu-api/src/main/java/app/soma.java
> +            throw new BadRequestException(String.format("Parâmetros inválidos: \\%s\\%s", op1, op2));
Poderia adicionar uma verificação para saber qual dos dois operandos é inválido.

2021-09-07 15:25 UTC, Angelina0liveira requested changes

2021-09-07 15:25 UTC, Angelina0liveira commented on calcu-api/src/main/java/app/soma.java
> +            throw new BadRequestException(String.format("Parâmetros inválidos: \\%s\\%s", op1, op2));
Poderia adicionar uma verificação para saber qual dos dois operandos inválido.

2021-09-14 19:45 UTC, KailaneSC commented on calcu-api/src/main/java/app/soma.java
> +            throw new BadRequestException(String.format("Parâmetros inválidos: \\%s\\%s", op1, op2));
A verificação dos parâmetros inválidos foi adicionada

2021-09-14 20:01 UTC, merged